### ISSUE TITLE
Use AMFPacket.Messages.Data in C# program

### ISSUE THREAD

**Issue by plenavi** [mtanksl/amf.net#2]
Not an issue per se, but I couldn't find anything elsewhere.

So I'm currently trying to create a program that reads AMF requests stored in a file (the file path passed through an argument in the terminal), and generates an AMF response based on the request.

I have a problem though: when reading an AMF packet and trying to read its data from its messages, I can't figure out a way to actually use the Data object in the message, I can only return its type through Console.WriteLine. This is probably due to my inexperience in C#, but can someone help me figure this out?

The included viewer can read the object just fine, so I probably am missing something here, but I can't figure out what.

Here's an extract of what I did:
```
                byte[] amfRequest = File.ReadAllBytes("the_path_to_my_file.req");
                var reader = new AmfReader(amfRequest);
                var packet = reader.ReadAmfPacket();

                Console.WriteLine(packet.Version);
                for (int i = 0; i < packet.Headers.Count; i++) {
                    var serializedHdr = packet.Headers[i].Data;
                    Console.WriteLine(serializedHdr);
                }
                for(int i = 0; i < packet.Messages.Count; i++)
                {
                    var serializedMsgTargetURI = packet.Messages[i].TargetUri;
                    var serializedMsgResponseURI = packet.Messages[i].ResponseUri;
                    var serializedMsgContent = packet.Messages[i].Data;

                    Console.WriteLine(serializedMsgTargetURI);
                    Console.WriteLine(serializedMsgResponseURI);
                    Console.WriteLine(serializedMsgContent);

                }
```
The terminal's output with a provided AMF request file:
![image](https://user-images.githubusercontent.com/98700367/224486700-d4d3715c-3662-4dbd-b1ab-118f18c6fa6b.png)

And here's the viewer's output using the same request:
![image](https://user-images.githubusercontent.com/98700367/224486519-9ff2eff5-757a-406f-9fe3-063059e6f126.png)

**Comment by mtanksl** [comment]
Hello sir,

Since we now know that the `packet.Messages[i].Data[0]` is an Amf3Object, you can cast it to Amf3Object like so:

```
 var serializedMsgContent = packet.Messages[i].Data;
 var amf3 = (Amf3Object)serializedMsgContent;
```

You can navigate the properties there. You can also try to deserialize it like so:

```
 var serializedMsgContent = packet.Messages[i].Data;
 var amf3 = (Amf3Object)serializedMsgContent;
 var obj = amf3.ToObject();
```

There are examples in `mtanksl.ActionMessageFormat.Tests/Amf3SerializationDeserialization.cs`

**Comment by plenavi** [comment]
Hello again,

Thank you for responding to my issue so quickly!
Though, sadly, trying to cast serializedMsgContent to an Amf3Object gives me yet another error:
![image](https://user-images.githubusercontent.com/98700367/224493534-7a9202af-d5a1-4d80-aefd-3484dbdea490.png)

**Comment by plenavi** [comment]
(didn't mean to close the issue)

**Comment by plenavi** [comment]
So I found a solution, the request just needed special treatment, so I'll be careful in the future when reproducing the requests I'm using. Thank you so much for your help!

(for anyone having the same problem: I had to change
`var amf3 = (Amf3Object)serializedMsgContent;`
to
`var amf3 = (List<object>)serializedMsgContent;`
because the request contained MORE than Amf3Objects (it also had a string!), which made the cast impossible.
Sorry if this is poorly written!)

**Comment by mtanksl** [comment]
Oh sorry, I missed the [0] index in my response. I meant:

```
 var serializedMsgContent = ((List<object>)packet.Messages[i].Data)[0];
 var amf3 = (Amf3Object)serializedMsgContent;
 var obj = amf3.ToObject();
```

You are right! Since your Data is a list of multiple objects, you must cast it to a list of objects first. From there you can iterate each item. If the item is an Amf3Object, you can try deserializing it. Thank you sir!
